<?php
// $Id$


/**
 * Implementation of hook_block().
 */
function on_the_web_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array('info' => t('On The Web'),
      'weight' => 0, 'status' => 1, 'region' => 'right');
    return $blocks;
  }
  elseif ($op == 'configure' && $delta == 0) {
    $form['twitter'] = array(
      '#type' => 'textfield',
      '#title' => t('Twitter Page'),
      '#default_value' => variable_get('on_the_web_twitter_page', ''),
      '#description' => t('Please paste the full url, including http://'),
    );
    $form['facebook'] = array(
      '#type' => 'textfield',
      '#title' => t('Facebook Page'),
      '#default_value' => variable_get('on_the_web_facebook_page', ''),
      '#description' => t('Please paste the full url, including http://'),
    );
    $form['youtube'] = array(
      '#type' => 'textfield',
      '#title' => t('YouTube Page'),
      '#default_value' => variable_get('on_the_web_youtube_page', ''),
      '#description' => t('Please paste the full url, including http://'),
    );
    $form['flickr'] = array(
      '#type' => 'textfield',
      '#title' => t('Flickr Page'),
      '#default_value' => variable_get('on_the_web_flickr_page', ''),
      '#description' => t('Please paste the full url, including http://'),
    );
    $form['myspace'] = array(
      '#type' => 'textfield',
      '#title' => t('MySpace Page'),
      '#default_value' => variable_get('on_the_web_myspace_page', ''),
      '#description' => t('Please paste the full url, including http://'),
    );
    $form['linkedin'] = array(
      '#type' => 'textfield',
      '#title' => t('LinkedIn Page'),
      '#default_value' => variable_get('on_the_web_linkedin_page', ''),
      '#description' => t('Please paste the full url, including http://'),
    );
    $form['sitename'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use Site Name in link titles'),
      '#default_value' => variable_get('on_the_web_sitename', TRUE),
      '#description' => t('You would prefer to use your !sitename in the title for these links.', array('!sitename' => l(t('Site name'), 'admin/settings/site-information'))),
    );
    return $form;
  }
  else if ($op == 'save' && $delta == 0) {
    variable_set('on_the_web_twitter_page', $edit['twitter']);
    variable_set('on_the_web_facebook_page', $edit['facebook']);
    variable_set('on_the_web_youtube_page', $edit['youtube']);
    variable_set('on_the_web_flickr_page', $edit['flickr']);
    variable_set('on_the_web_myspace_page', $edit['myspace']);
    variable_set('on_the_web_linkedin_page', $edit['linkedin']);
    variable_set('on_the_web_sitename', $edit['sitename']);
  }
  else if ($op == 'view') {
    switch($delta) {
      case 0:
        $block = array('subject' => t('Find Us On...'),
          'content' => on_the_web_display_block_0());
        break;
    }
    return $block;
  }
}

/**
 * Block Display
 *
 * @return 
 *    Content for block.
 */
function on_the_web_display_block_0(){
  $module_path = drupal_get_path('module', 'on_the_web');
  
  if (!(variable_get('on_the_web_sitename', TRUE) && ($name = variable_get('site_name', FALSE)))){
    $name = t('Us');
  }
  
  $services = array(
    'twitter' => array('name' => 'Twitter'),
    'facebook' => array('name' => 'Facebook'),
    'youtube' => array('name' => 'YouTube'),
    'flickr' => array('name' => 'Flickr'),
    'myspace' => array('name' => 'MySpace'),
    'linkedin' => array('name' => 'LinkedIn'),
    );
  
  $output = '';  
  foreach ($services as $service => $info){
    $page = variable_get('on_the_web_'.$service.'_page', FALSE);
    if ($page){
      $title = t('Find !us on !service', array('!us' => $name, '!service' => $info['name']));
      $image = theme('image', $module_path.'/images/logo-' . $service . '.png', $title, $title);
      $attributes  = array('title' => $title, 'target' => '_blank');
      $linked_image = l($image, $page, array('attributes' => $attributes, 'html' => TRUE));
      $output .= theme('on_the_web_icon', $linked_image);
    }
  }  

  return $output;
}

/**
 * Implementation of hook_theme().
 */
function on_the_web_theme($existing, $type, $theme, $path) {
  return array(
    'on_the_web_icon' => array(
      'arguments' => array('linked_image' => NULL),
    ),
  );
}

/**
 * Theme function
 *
 * @param $linked_image
 *    Linked icon.
 * @return 
 *    Linked icon with wrapper markup.
 */
function theme_on_the_web_icon($linked_image){
  if ($linked_image){
    $output = '<span class="on-the-web">' . $linked_image . '</span>';
    return $output;
  }
  return;
}
