<?php 
/**
 * @file
 * Install, update and uninstall functions for the on_the_web module.
 */

/**
 * Implementation of hook_uninstall().
 *
 * Deletes all module-specific variables on uninstall.
 */
function on_the_web_uninstall() {
  $services = on_the_web_get_services();
  foreach ($servies as $service) {
    variable_del('on_the_web_' . $service . '_page');
  }
  variable_del('on_the_web_feed');
  variable_del('on_the_web_target');
  variable_del('on_the_web_sitename');
}